name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Premium Snake
        uses: Platane/snk@v3
        with:
          github_user_name: akhlaque03
          outputs: |
            "dist/github-contribution-grid-snake.svg?color_snake=%23FFFFFF&color_dots=%230B1020,%2300E5FF,%237C3AED,%23FF4FD8,%23FF2D95"
            "dist/github-contribution-grid-snake-dark.svg?color_snake=%23FFFFFF&color_dots=%230B1020,%2300E5FF,%237C3AED,%23FF4FD8,%23FF2D95"

      - name: Publish Premium Snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
